name = "sieve_of_eratosthenes"
version = "0.1.0"
license = "license"
author = "gobytis"
copyright = "Copyright 2023, gobytis"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
argument_getter = {git = "https://github.com/gobytis/Fortran-argument-getter"}
